Vagrant.configure(2) do |config|
 config.vm.box = "centos/7"
 config.vm.hostname = 'node1.example.com'
 config.vm.network "private_network", type: "dhcp"
 config.vm.provision "shell", inline: "groupadd docker; usermod -aG docker vagrant; yum install docker -y; systemctl enable docker; systemctl start docker"
end
